"""Produce exact rational witnesses; Lean independently proves every inequality.

No floating-point or external numerical result is trusted by the formalization.
The remainder estimate is proved in LogEnclosure.lean.
"""
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TAILS = {'A6':[3,6,10,15], 'A7':[3,6,10,15,21],
         'E6':[3,4,8,9], 'E7':[3,4,8,9,11]}
SCALE = 10**13

def q(x):
    x=F(x)
    return f'({x.numerator}:ℝ)/{x.denominator}'

def floorq(x,scale):
    return F((x*scale).__floor__(),scale)

def ceilq(x,scale):
    return F((x*scale).__ceil__(),scale)

def Z(key,x):
    return 1+x+sum(x**b for b in TAILS[key])

def mean(key,x):
    return (x+sum(b*x**b for b in TAILS[key]))/Z(key,x)

def approx(x):
    eta=(x-1)/(x+1)
    N=2
    while 2*abs(eta)**(N+1)/(1-abs(eta))>F(1,10**15):
        N+=2
    v=sum((eta**(i+1)-(-eta)**(i+1))/(i+1) for i in range(N))
    err=2*abs(eta)**(N+1)/(1-abs(eta))
    return N,v-err,v+err

parts=['''import HoffmanChromatic.LogEnclosure
import HoffmanChromatic.RateBracket
import HoffmanChromatic.SharpParameters

/-! Exact witnesses for the four crossing rows. Generated by
tools/generate_sharp_certificates.py; every proof is checked by Lean. -/
namespace HoffmanChromatic
set_option maxRecDepth 16384
set_option maxHeartbeats 0
''']
logs={}

def logcert(name,x,expr=None,key=None):
    expr=expr or q(x)
    lo,hi=floorq(x,10**15),ceilq(x,10**15)
    N,L,_=approx(lo)
    M,_,U=approx(hi)
    L,U=floorq(L,SCALE),ceilq(U,SCALE)
    unfold=f',partition01,tail{key},Fin.sum_univ_succ' if key else ''
    parts.append(f'''private theorem log_{name} :
    {q(L)}≤Real.log ({expr}) ∧ Real.log ({expr})≤{q(U)} := by
  apply log_between_of_series ({expr}) ({q(lo)}) ({q(hi)}) _ _ {N} {M}
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div{unfold}]
''')
    logs[name]=(L,U)
    return L,U

rates={}
def ratecert(name,key,m,l,u):
    assert mean(key,l)<m<mean(key,u)
    LZ,UZ=logcert(name+'_Z',Z(key,l),f'partition01 tail{key} ({q(l)})',key)
    Ll,Ul=logcert(name+'_x',l)
    low=floorq(LZ-m*Ul-(m-mean(key,l))*(u/l-1),SCALE)
    high=ceilq(UZ-m*Ll,SCALE)
    parts.append(f'''private theorem rate_{name} :
    {q(low)}≤logarithmicRate (partition01 tail{key}) ({q(m)}) ∧
    logarithmicRate (partition01 tail{key}) ({q(m)})≤{q(high)} := by
  have h := logarithmicRate_numeric_bound tail{key} ({q(l)}) ({q(u)}) ({q(m)})
    ({q(LZ)}) ({q(UZ)}) ({q(Ll)}) ({q(Ul)})
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tail{key},Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tail{key},Fin.sum_univ_succ])
    log_{name}_Z log_{name}_x
  have hm : mean01 tail{key} ({q(l)})={q(mean(key,l))} := by
    norm_num [mean01,partition01,tail{key},Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]
''')
    rates[name]=(low,high)
    return low,high

rows=[('six_left','6',F(371979,10**6),562503,342209,269455401,269455403),
      ('seven_left','7',F(743958,10**6),733755,517230,269455447,269455448),
      ('six_right','6',F(371980,10**6),562504,342210,269455480,269455481),
      ('seven_right','7',F(743960,10**6),733755,517231,269455367,269455368)]
for name,Q,d,kt,ks,lower,upper in rows:
    a=ratecert(name+'_A','A'+Q,2*d,F(kt,10**6),F(kt+1,10**6))
    e=ratecert(name+'_E','E'+Q,d,F(ks,10**6),F(ks+1,10**6))
    assert F(lower,10**9)<a[0]-e[1] and a[1]-e[0]<F(upper,10**9)
    parts.append(f'''theorem crossing_row_{name} :
    {q(F(lower,10**9))}<delta{Q} ({q(d)}) ∧ delta{Q} ({q(d)})<{q(F(upper,10**9))} := by
  have hA := rate_{name}_A
  have hE := rate_{name}_E
  have hAp : partition01 tailA{Q}=realA{Q} := funext partition01_A{Q}
  have hEp : partition01 tailE{Q}=realE{Q} := funext partition01_E{Q}
  rw [hAp] at hA
  rw [hEp] at hE
  norm_num [delta{Q}]
  constructor <;> linarith only [hA.1,hA.2,hE.1,hE.2]
''')

for name,v in [('base_lower',F(1309251,10**6)),('base_upper',F(1309252,10**6))]:
    logcert(name,v)
parts.append('''theorem crossing_base_log_bounds :
    Real.log ((1309251:ℝ)/1000000)<(269455219:ℝ)/1000000000 ∧
    (269455900:ℝ)/1000000000<Real.log ((1309252:ℝ)/1000000) := by
  have hL := log_base_lower
  have hU := log_base_upper
  constructor <;> linarith only [hL.1,hL.2,hU.1,hU.2]
''')
parts.append('end HoffmanChromatic\n')
(ROOT/'HoffmanChromatic'/'SharpCertificates.lean').write_text('\n'.join(parts))
print(f'Generated {len(logs)} logarithm enclosures, {len(rates)} rate enclosures, and four crossing rows.')

parts=['''import HoffmanChromatic.LogEnclosure
import HoffmanChromatic.RateCover
import HoffmanChromatic.SharpParameters

/-! The six interior endpoint inequalities, each valid on the stated s-box. -/
namespace HoffmanChromatic
set_option maxRecDepth 16384
set_option maxHeartbeats 0
''']
logs={}
rates={}
for name,Q,d,k in [('six_042','6',F(21,50),595),('six_055','6',F(11,20),665),
                   ('seven_055','7',F(11,20),664),('seven_068','7',F(17,25),714)]:
    ratecert(name,'A'+Q,2*d,F(k,1000),F(k+1,1000))
interior_rows=[
    ('six_042','6',F(21,50),F(342209,10**6),F(342211,10**6),F(270365,10**6)),
    ('six_042','6',F(21,50),F(2,5),F(2,5),F(270573,10**6)),
    ('six_055','6',F(11,20),F(2,5),F(2,5),F(270652,10**6)),
    ('seven_055','7',F(11,20),F(12,25),F(12,25),F(270484,10**6)),
    ('seven_068','7',F(17,25),F(12,25),F(12,25),F(271274,10**6)),
    ('seven_068','7',F(17,25),F(517230,10**6),F(517232,10**6),F(270342,10**6)),
]
cache={}
for index,(name,Q,d,l,u,target) in enumerate(interior_rows,1):
    if (Q,l,u) not in cache:
        zn=f'interior_{index}_Z'; ln=f'interior_{index}_s'
        zlogs=logcert(zn,Z('E'+Q,u),f'partition01 tailE{Q} ({q(u)})','E'+Q)
        llogs=logcert(ln,l)
        cache[Q,l,u]=(zn,ln,zlogs,llogs)
    zn,ln,zlogs,llogs=cache[Q,l,u]
    low=rates[name][0]
    assert target<low-zlogs[1]+d*llogs[0]
    parts.append(f'''theorem interior_minorant_{index} (s : ℝ)
    (hsl : {q(l)}≤s) (hsu : s≤{q(u)}) :
    {q(target)}<rateMinorant tailA{Q} tailE{Q} s ({q(d)}) := by
  have hA : {q(low)}≤logarithmicRate (partition01 tailA{Q}) (2*({q(d)})) := by
    convert rate_{name}.1 using 1; norm_num
  have h := rateMinorant_box_lower tailA{Q} tailE{Q} ({q(d)}) s ({q(l)}) ({q(u)})
    ({q(low)}) ({q(zlogs[1])}) ({q(llogs[0])}) (by norm_num) (by norm_num) hsl hsu
    hA log_{zn}.2 log_{ln}.1
  linarith only [h]
''')
parts.append('end HoffmanChromatic\n')
(ROOT/'HoffmanChromatic'/'InteriorCertificates.lean').write_text('\n'.join(parts))
print(f'Generated {len(logs)} interior logarithm enclosures and six endpoint bounds.')
