import HoffmanChromatic.LogEnclosure
import HoffmanChromatic.RateBracket
import HoffmanChromatic.SharpParameters

/-! Exact witnesses for the four crossing rows. Generated by
tools/generate_sharp_certificates.py; every proof is checked by Lean. -/
namespace HoffmanChromatic
set_option maxRecDepth 16384
set_option maxHeartbeats 0

private theorem log_six_left_A_Z :
    (5740886666931:ℝ)/10000000000000≤Real.log (partition01 tailA6 ((562503:ℝ)/1000000)) ∧ Real.log (partition01 tailA6 ((562503:ℝ)/1000000))≤(1435221666733:ℝ)/2500000000000 := by
  apply log_between_of_series (partition01 tailA6 ((562503:ℝ)/1000000)) ((1775511706428863:ℝ)/1000000000000000) ((27742370412951:ℝ)/15625000000000) _ _ 28 28
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailA6,Fin.sum_univ_succ]

private theorem log_six_left_A_x :
    (-1150717623169:ℝ)/2000000000000≤Real.log ((562503:ℝ)/1000000) ∧ Real.log ((562503:ℝ)/1000000)≤(-1438397028961:ℝ)/2500000000000 := by
  apply log_between_of_series ((562503:ℝ)/1000000) ((562503:ℝ)/1000000) ((562503:ℝ)/1000000) _ _ 28 28
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_six_left_A :
    (10021314574397:ℝ)/10000000000000≤logarithmicRate (partition01 tailA6) ((371979:ℝ)/500000) ∧
    logarithmicRate (partition01 tailA6) ((371979:ℝ)/500000)≤(501065728721:ℝ)/500000000000 := by
  have h := logarithmicRate_numeric_bound tailA6 ((562503:ℝ)/1000000) ((70313:ℝ)/125000) ((371979:ℝ)/500000)
    ((5740886666931:ℝ)/10000000000000) ((1435221666733:ℝ)/2500000000000) ((-1150717623169:ℝ)/2000000000000) ((-1438397028961:ℝ)/2500000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailA6,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailA6,Fin.sum_univ_succ])
    log_six_left_A_Z log_six_left_A_x
  have hm : mean01 tailA6 ((562503:ℝ)/1000000)=(1320904040376488664735854946847530748206078291272449394342485003775111304750875754885546105:ℝ)/1775511706428863224171404088088073856586593707588571292350848666918340753650058383659036407 := by
    norm_num [mean01,partition01,tailA6,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

private theorem log_six_left_E_Z :
    (1668952343711:ℝ)/5000000000000≤Real.log (partition01 tailE6 ((342209:ℝ)/1000000)) ∧ Real.log (partition01 tailE6 ((342209:ℝ)/1000000))≤(3337904687423:ℝ)/10000000000000 := by
  apply log_between_of_series (partition01 tailE6 ((342209:ℝ)/1000000)) ((27925011095749:ℝ)/20000000000000) ((1396250554787451:ℝ)/1000000000000000) _ _ 20 20
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailE6,Fin.sum_univ_succ]

private theorem log_six_left_E_x :
    (-670208510913:ℝ)/625000000000≤Real.log ((342209:ℝ)/1000000) ∧ Real.log ((342209:ℝ)/1000000)≤(-10723336174607:ℝ)/10000000000000 := by
  apply log_between_of_series ((342209:ℝ)/1000000) ((342209:ℝ)/1000000) ((342209:ℝ)/1000000) _ _ 50 50
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_six_left_E :
    (3663380277141:ℝ)/5000000000000≤logarithmicRate (partition01 tailE6) ((371979:ℝ)/1000000) ∧
    logarithmicRate (partition01 tailE6) ((371979:ℝ)/1000000)≤(3663380277159:ℝ)/5000000000000 := by
  have h := logarithmicRate_numeric_bound tailE6 ((342209:ℝ)/1000000) ((34221:ℝ)/100000) ((371979:ℝ)/1000000)
    ((1668952343711:ℝ)/5000000000000) ((3337904687423:ℝ)/10000000000000) ((-670208510913:ℝ)/625000000000) ((-10723336174607:ℝ)/10000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailE6,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailE6,Fin.sum_univ_succ])
    log_six_left_E_Z log_six_left_E_x
  have hm : mean01 tailE6 ((342209:ℝ)/1000000)=(519374255542369088845944906886448791809453881527846601:ℝ)/1396250554787450008921087195591013436552773020294316289 := by
    norm_num [mean01,partition01,tailE6,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

theorem crossing_row_six_left :
    (269455401:ℝ)/1000000000<delta6 ((371979:ℝ)/1000000) ∧ delta6 ((371979:ℝ)/1000000)<(269455403:ℝ)/1000000000 := by
  have hA := rate_six_left_A
  have hE := rate_six_left_E
  have hAp : partition01 tailA6=realA6 := funext partition01_A6
  have hEp : partition01 tailE6=realE6 := funext partition01_E6
  rw [hAp] at hA
  rw [hEp] at hE
  norm_num [delta6]
  constructor <;> linarith only [hA.1,hA.2,hE.1,hE.2]

private theorem log_seven_left_A_Z :
    (4253390335617:ℝ)/5000000000000≤Real.log (partition01 tailA7 ((146751:ℝ)/200000)) ∧ Real.log (partition01 tailA7 ((146751:ℝ)/200000))≤(1701356134247:ℝ)/2000000000000 := by
  apply log_between_of_series (partition01 tailA7 ((146751:ℝ)/200000)) ((1170616913757021:ℝ)/500000000000000) ((2341233827514043:ℝ)/1000000000000000) _ _ 40 40
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailA7,Fin.sum_univ_succ]

private theorem log_seven_left_A_x :
    (-309580093553:ℝ)/1000000000000≤Real.log ((146751:ℝ)/200000) ∧ Real.log ((146751:ℝ)/200000)≤(-3095800935529:ℝ)/10000000000000 := by
  apply log_between_of_series ((146751:ℝ)/200000) ((146751:ℝ)/200000) ((146751:ℝ)/200000) _ _ 18 18
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_seven_left_A :
    (2622614483197:ℝ)/2000000000000≤logarithmicRate (partition01 tailA7) ((371979:ℝ)/250000) ∧
    logarithmicRate (partition01 tailA7) ((371979:ℝ)/250000)≤(6556536208013:ℝ)/5000000000000 := by
  have h := logarithmicRate_numeric_bound tailA7 ((146751:ℝ)/200000) ((183439:ℝ)/250000) ((371979:ℝ)/250000)
    ((4253390335617:ℝ)/5000000000000) ((1701356134247:ℝ)/2000000000000) ((-309580093553:ℝ)/1000000000000) ((-3095800935529:ℝ)/10000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailA7,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailA7,Fin.sum_univ_succ])
    log_seven_left_A_Z log_seven_left_A_x
  have hm : mean01 tailA7 ((146751:ℝ)/200000)=(1043648582746728108172951675643506100079696497733979162907820821347118398576984535181584358545520707211476120253:ℝ)/701417600548389925916620613667909667124375613508623896881935790750022025814722259389599255168834319391022672393 := by
    norm_num [mean01,partition01,tailA7,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

private theorem log_seven_left_E_Z :
    (5513843669553:ℝ)/10000000000000≤Real.log (partition01 tailE7 ((51723:ℝ)/100000)) ∧ Real.log (partition01 tailE7 ((51723:ℝ)/100000))≤(2756921834777:ℝ)/5000000000000 := by
  apply log_between_of_series (partition01 tailE7 ((51723:ℝ)/100000)) ((867827068851279:ℝ)/500000000000000) ((1735654137702559:ℝ)/1000000000000000) _ _ 28 28
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailE7,Fin.sum_univ_succ]

private theorem log_seven_left_E_x :
    (-6592676291263:ℝ)/10000000000000≤Real.log ((51723:ℝ)/100000) ∧ Real.log ((51723:ℝ)/100000)≤(-3296338145631:ℝ)/5000000000000 := by
  apply log_between_of_series ((51723:ℝ)/100000) ((51723:ℝ)/100000) ((51723:ℝ)/100000) _ _ 32 32
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_seven_left_E :
    (416740717513:ℝ)/400000000000≤logarithmicRate (partition01 tailE7) ((371979:ℝ)/500000) ∧
    logarithmicRate (partition01 tailE7) ((371979:ℝ)/500000)≤(208370358757:ℝ)/200000000000 := by
  have h := logarithmicRate_numeric_bound tailE7 ((51723:ℝ)/100000) ((517231:ℝ)/1000000) ((371979:ℝ)/500000)
    ((5513843669553:ℝ)/10000000000000) ((2756921834777:ℝ)/5000000000000) ((-6592676291263:ℝ)/10000000000000) ((-3296338145631:ℝ)/5000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailE7,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailE7,Fin.sum_univ_succ])
    log_seven_left_E_Z log_seven_left_E_x
  have hm : mean01 tailE7 ((51723:ℝ)/100000)=(12912517895462278236975190383812599675779017340788452497:ℝ)/17356541377025585366949426685737766873088893872798950227 := by
    norm_num [mean01,partition01,tailE7,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

theorem crossing_row_seven_left :
    (269455447:ℝ)/1000000000<delta7 ((371979:ℝ)/500000) ∧ delta7 ((371979:ℝ)/500000)<(33681931:ℝ)/125000000 := by
  have hA := rate_seven_left_A
  have hE := rate_seven_left_E
  have hAp : partition01 tailA7=realA7 := funext partition01_A7
  have hEp : partition01 tailE7=realE7 := funext partition01_E7
  rw [hAp] at hA
  rw [hEp] at hE
  norm_num [delta7]
  constructor <;> linarith only [hA.1,hA.2,hE.1,hE.2]

private theorem log_six_right_A_Z :
    (1435224973193:ℝ)/2500000000000≤Real.log (partition01 tailA6 ((70313:ℝ)/125000)) ∧ Real.log (partition01 tailA6 ((70313:ℝ)/125000))≤(5740899892773:ℝ)/10000000000000 := by
  apply log_between_of_series (partition01 tailA6 ((70313:ℝ)/125000)) ((1733900444037:ℝ)/976562500000) ((1775514054693889:ℝ)/1000000000000000) _ _ 28 28
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailA6,Fin.sum_univ_succ]

private theorem log_six_right_A_x :
    (-2876785169089:ℝ)/5000000000000≤Real.log ((70313:ℝ)/125000) ∧ Real.log ((70313:ℝ)/125000)≤(-5753570338177:ℝ)/10000000000000 := by
  apply log_between_of_series ((70313:ℝ)/125000) ((70313:ℝ)/125000) ((70313:ℝ)/125000) _ _ 28 28
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_six_right_A :
    (10021326081553:ℝ)/10000000000000≤logarithmicRate (partition01 tailA6) ((18599:ℝ)/25000) ∧
    logarithmicRate (partition01 tailA6) ((18599:ℝ)/25000)≤(2505331520391:ℝ)/2500000000000 := by
  have h := logarithmicRate_numeric_bound tailA6 ((70313:ℝ)/125000) ((112501:ℝ)/200000) ((18599:ℝ)/25000)
    ((1435224973193:ℝ)/2500000000000) ((5740899892773:ℝ)/10000000000000) ((-2876785169089:ℝ)/5000000000000) ((-5753570338177:ℝ)/10000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailA6,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailA6,Fin.sum_univ_succ])
    log_six_right_A_Z log_six_right_A_x
  have hm : mean01 tailA6 ((70313:ℝ)/125000)=(37542535854396987598912613723964481515293157595029871710510251284045302868855:ℝ)/50463144552108140795963519797268593882218616184241096671976725085603020191257 := by
    norm_num [mean01,partition01,tailA6,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

private theorem log_six_right_E_Z :
    (3337915557331:ℝ)/10000000000000≤Real.log (partition01 tailE6 ((34221:ℝ)/100000)) ∧ Real.log (partition01 tailE6 ((34221:ℝ)/100000))≤(834478889333:ℝ)/2500000000000 := by
  apply log_between_of_series (partition01 tailE6 ((34221:ℝ)/100000)) ((174531509062491:ℝ)/125000000000000) ((1396252072499929:ℝ)/1000000000000000) _ _ 20 20
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailE6,Fin.sum_univ_succ]

private theorem log_six_right_E_x :
    (-10723306952743:ℝ)/10000000000000≤Real.log ((34221:ℝ)/100000) ∧ Real.log ((34221:ℝ)/100000)≤(-5361653476371:ℝ)/5000000000000 := by
  apply log_between_of_series ((34221:ℝ)/100000) ((34221:ℝ)/100000) ((34221:ℝ)/100000) _ _ 50 50
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_six_right_E :
    (3663385638797:ℝ)/5000000000000≤logarithmicRate (partition01 tailE6) ((18599:ℝ)/50000) ∧
    logarithmicRate (partition01 tailE6) ((18599:ℝ)/50000)≤(3663385638807:ℝ)/5000000000000 := by
  have h := logarithmicRate_numeric_bound tailE6 ((34221:ℝ)/100000) ((342211:ℝ)/1000000) ((18599:ℝ)/50000)
    ((3337915557331:ℝ)/10000000000000) ((834478889333:ℝ)/2500000000000) ((-10723306952743:ℝ)/10000000000000) ((-5361653476371:ℝ)/5000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailE6,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailE6,Fin.sum_univ_succ])
    log_six_right_E_Z log_six_right_E_x
  have hm : mean01 tailE6 ((34221:ℝ)/100000)=(519377001120844342807165096275043331836821429:ℝ)/1396252072499928272196452813509098547948102381 := by
    norm_num [mean01,partition01,tailE6,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

theorem crossing_row_six_right :
    (6736387:ℝ)/25000000<delta6 ((18599:ℝ)/50000) ∧ delta6 ((18599:ℝ)/50000)<(269455481:ℝ)/1000000000 := by
  have hA := rate_six_right_A
  have hE := rate_six_right_E
  have hAp : partition01 tailA6=realA6 := funext partition01_A6
  have hEp : partition01 tailE6=realE6 := funext partition01_E6
  rw [hAp] at hA
  rw [hEp] at hE
  norm_num [delta6]
  constructor <;> linarith only [hA.1,hA.2,hE.1,hE.2]

private theorem log_seven_right_A_Z :
    (4253390335617:ℝ)/5000000000000≤Real.log (partition01 tailA7 ((146751:ℝ)/200000)) ∧ Real.log (partition01 tailA7 ((146751:ℝ)/200000))≤(1701356134247:ℝ)/2000000000000 := by
  apply log_between_of_series (partition01 tailA7 ((146751:ℝ)/200000)) ((1170616913757021:ℝ)/500000000000000) ((2341233827514043:ℝ)/1000000000000000) _ _ 40 40
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailA7,Fin.sum_univ_succ]

private theorem log_seven_right_A_x :
    (-309580093553:ℝ)/1000000000000≤Real.log ((146751:ℝ)/200000) ∧ Real.log ((146751:ℝ)/200000)≤(-3095800935529:ℝ)/10000000000000 := by
  apply log_between_of_series ((146751:ℝ)/200000) ((146751:ℝ)/200000) ((146751:ℝ)/200000) _ _ 18 18
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_seven_right_A :
    (2622616959827:ℝ)/2000000000000≤logarithmicRate (partition01 tailA7) ((18599:ℝ)/12500) ∧
    logarithmicRate (partition01 tailA7) ((18599:ℝ)/12500)≤(13113084799229:ℝ)/10000000000000 := by
  have h := logarithmicRate_numeric_bound tailA7 ((146751:ℝ)/200000) ((183439:ℝ)/250000) ((18599:ℝ)/12500)
    ((4253390335617:ℝ)/5000000000000) ((1701356134247:ℝ)/2000000000000) ((-309580093553:ℝ)/1000000000000) ((-3095800935529:ℝ)/10000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailA7,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailA7,Fin.sum_univ_succ])
    log_seven_right_A_Z log_seven_right_A_x
  have hm : mean01 tailA7 ((146751:ℝ)/200000)=(1043648582746728108172951675643506100079696497733979162907820821347118398576984535181584358545520707211476120253:ℝ)/701417600548389925916620613667909667124375613508623896881935790750022025814722259389599255168834319391022672393 := by
    norm_num [mean01,partition01,tailA7,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

private theorem log_seven_right_E_Z :
    (5513858053049:ℝ)/10000000000000≤Real.log (partition01 tailE7 ((517231:ℝ)/1000000)) ∧ Real.log (partition01 tailE7 ((517231:ℝ)/1000000))≤(110277161061:ℝ)/200000000000 := by
  apply log_between_of_series (partition01 tailE7 ((517231:ℝ)/1000000)) ((867828317090901:ℝ)/500000000000000) ((1735656634181803:ℝ)/1000000000000000) _ _ 28 28
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div,partition01,tailE7,Fin.sum_univ_succ]

private theorem log_seven_right_E_x :
    (-6592656957523:ℝ)/10000000000000≤Real.log ((517231:ℝ)/1000000) ∧ Real.log ((517231:ℝ)/1000000)≤(-3296328478761:ℝ)/5000000000000 := by
  apply log_between_of_series ((517231:ℝ)/1000000) ((517231:ℝ)/1000000) ((517231:ℝ)/1000000) _ _ 32 32
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem rate_seven_right_E :
    (10418531123161:ℝ)/10000000000000≤logarithmicRate (partition01 tailE7) ((18599:ℝ)/25000) ∧
    logarithmicRate (partition01 tailE7) ((18599:ℝ)/25000)≤(10418531123169:ℝ)/10000000000000 := by
  have h := logarithmicRate_numeric_bound tailE7 ((517231:ℝ)/1000000) ((32327:ℝ)/62500) ((18599:ℝ)/25000)
    ((5513858053049:ℝ)/10000000000000) ((110277161061:ℝ)/200000000000) ((-6592656957523:ℝ)/10000000000000) ((-3296328478761:ℝ)/5000000000000)
    (by norm_num) (by norm_num) (by norm_num) (by norm_num)
    (by norm_num [mean01,partition01,tailE7,Fin.sum_univ_succ])
    (by norm_num [mean01,partition01,tailE7,Fin.sum_univ_succ])
    log_seven_right_E_Z log_seven_right_E_x
  have hm : mean01 tailE7 ((517231:ℝ)/1000000)=(1291258625820232279269251343112255824667008799925019407228411194341:ℝ)/1735656634181802663188104607374375521610462474355486759020764654031 := by
    norm_num [mean01,partition01,tailE7,Fin.sum_univ_succ]
  rw [hm] at h
  norm_num at h
  constructor <;> linarith only [h.1,h.2]

theorem crossing_row_seven_right :
    (269455367:ℝ)/1000000000<delta7 ((18599:ℝ)/25000) ∧ delta7 ((18599:ℝ)/25000)<(33681921:ℝ)/125000000 := by
  have hA := rate_seven_right_A
  have hE := rate_seven_right_E
  have hAp : partition01 tailA7=realA7 := funext partition01_A7
  have hEp : partition01 tailE7=realE7 := funext partition01_E7
  rw [hAp] at hA
  rw [hEp] at hE
  norm_num [delta7]
  constructor <;> linarith only [hA.1,hA.2,hE.1,hE.2]

private theorem log_base_lower :
    (673638044933:ℝ)/2500000000000≤Real.log ((1309251:ℝ)/1000000) ∧ Real.log ((1309251:ℝ)/1000000)≤(2694552179733:ℝ)/10000000000000 := by
  apply log_between_of_series ((1309251:ℝ)/1000000) ((1309251:ℝ)/1000000) ((1309251:ℝ)/1000000) _ _ 18 18
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

private theorem log_base_upper :
    (673639954421:ℝ)/2500000000000≤Real.log ((327313:ℝ)/250000) ∧ Real.log ((327313:ℝ)/250000)≤(538911963537:ℝ)/2000000000000 := by
  apply log_between_of_series ((327313:ℝ)/250000) ((327313:ℝ)/250000) ((327313:ℝ)/250000) _ _ 18 18
  all_goals norm_num [logApprox,logTaylorSum,logEta,logError,Finset.sum_range_succ,abs_div]

theorem crossing_base_log_bounds :
    Real.log ((1309251:ℝ)/1000000)<(269455219:ℝ)/1000000000 ∧
    (269455900:ℝ)/1000000000<Real.log ((1309252:ℝ)/1000000) := by
  have hL := log_base_lower
  have hU := log_base_upper
  constructor <;> linarith only [hL.1,hL.2,hU.1,hU.2]

end HoffmanChromatic
